---
- name: Converge
  hosts: all
  vars:
    firefox_profiles:
      default:
        extensions:
          - ublock-origin

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Ensure dependencies are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-requests

  tasks:
    - name: "Include staticdev.firefox"
      ansible.builtin.include_role:
        name: "staticdev.firefox"
